import './globals.css'

export const metadata = {
  title: 'Buy Amazing Events',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"

        />
      </head>

      <body>{children}</body>
    </html>
  )
}
